### ISSUE TITLE
Listing a set of icons

### ISSUE THREAD

**Issue by Jzarecta** [Dirrot/python-cryptocoincharts-api#5]
Have been getting issues trying to list the transaction price, I am using python3:

``` python
>>> if __name__ == '__main__':
...     pairs = 'ltc_btc, doge_btc, eth_btc, rby_btc, efl_btc, dash_btc, nxt_btc, rby_btc, start_btc'
...     api = API()
...     tradingpairs = api.tradingpairs(pairs.encode('utf-8'))
...     for tradingpair in tradingpairs:
...             print(tradingpair)
... 
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/jza/Downloads/python-cryptocoincharts-api/CryptoCoinChartsApi/CryptoCoinChartsApi.py", line 78, in tradingpairs
    json_data = json.loads(self._getdata(url, data))
  File "/home/jza/Downloads/python-cryptocoincharts-api/CryptoCoinChartsApi/CryptoCoinChartsApi.py", line 108, in _getdata
    response = urlopen(request)
  File "/usr/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 463, in open
    req = meth(req)
  File "/usr/lib/python3.5/urllib/request.py", line 1170, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes or an iterable of bytes. It cannot be of type str.
```

**Comment by Dirrot** [comment]
Please use pyhton2.
